name: Code Compilation

on: pull_request

jobs:
  type-check:
    name: Type Check
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run type:check

  build:
    needs: type-check
    name: Build
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run build
