name: e2e tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run dev
          wait-on: "http://localhost:5173"
