name: Format & Lint

on: pull_request

jobs:
  format-and-lint:
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run format:check
        npm run lint
        npm run css:lint
    # steps:
    #   - name: Checkout repo
    #     uses: actions/checkout@v4
    #   - name: Install dependencies
    #     run: npm install
    #     working-directory: .
    #   - name: Format
    #     run: npm run format:check
    #     working-directory: .
    #   - name: Lint
    #     run: npm run lint
    #     working-directory: .
    #   - name: Style Lint
    #     run: npm run css:lint
    #     working-directory: .
