name: Format & Lint

on: [pull_request]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: .
      - name: Format
        run: npm run format:check
        working-directory: .
      - name: Lint
        run: npm run lint
        working-directory: .
