name: Tests
on: 
  pull_request:
    branches: ["develop"]
jobs:
  e2e-tests:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: "http://localhost:5173"
  unit-tests:
    name: Unit
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run test:unit
